openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
paths:
  /users:
    post:
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDto'
      responses:
        '204':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDto'
  /posts:
    post:
      operationId: createPost
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostDto'
      responses:
        '204':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostDto'
components:
  schemas:
    UserDto:
      type: object
      properties:
        userId:
          type: integer
        username:
          type: string
        email:
          type: string
          format: email
    PostDto:
      type: object
      properties:
        postId:
          type: integer
        title:
          type: string
        content:
          type: string
        createdAt:
          type: string
          format: date-time
        userId:
          type: integer
          format: int64